name: ssvep-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6,<3.8
  - numpy
  - numpy>=1.17.3,<1.18
  - scikit-learn>=0.22.1,<0.23
  - pandas>=0.23.4,<0.24
  - scipy>=1.1
  - h5py
  # to run the notebooks
  - jupyter
  - matplotlib
  - seaborn
  # Extra pip dependencies
  - pip
  - pip:
      - mne>=0.19,<0.20
      - git+https://github.com/NeuroTechX/moabb#egg=moabb
      - git+https://github.com/bertrandlalo/pyRiemann
      - git+https://github.com/timeflux/timeflux.git@194aaf6#egg=timeflux
      - git+https://github.com/timeflux/timeflux_bci.git@9407f7b#egg=timeflux_bci
